example.property: "I AM A DEFAULT LICENSING SERVICE"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://msa-db-dev.cibmkkh3emmo.ap-northeast-1.rds.amazonaws.com:5432/eagle_eye_local"
spring.datasource.username: "postgres"
spring.datasource.password: "{cipher}c792a1cfcdae159fb5a91981e820858e5e8e44d390421cf9727cded01b2115d6"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"